### ISSUE TITLE
11月3日MVP依頼

### ISSUE THREAD

**Issue by hataboon** [hataboon/pakuraku_app#14]

**Comment by Tsuchiya2** [comment]
<img width="977" alt="image" src="https://github.com/user-attachments/assets/32ae1bac-d307-4c47-8ce2-d85efa6611d2" />

issueの概要に何も書かれていないので、このissueが何のためのissueなのかが分かりかねました。↑のご確認と対応をお願いします。

**Comment by hataboon** [comment]
## 各種情報
サービスの概要とMVPで検証する事柄：
- サービス概要：生成 AI が栄養を考えた献立を提案します。また、摂取した栄養の可視化機能も提供します。
- MVPで検証してほしい部分：基本的な献立生成の操作性、ログイン機能の動作確認
サービス名： パクラク（献立提案アプリ）

サービスURL：https://pakuraku-app.onrender.com/


## READMEレビュー時にMVPリリース時点で実装予定だった機能
- 食材入力・栄養素に基づく献立生成
- 新規登録・ログイン機能

## READMEレビュー時から変更した機能
- 当初、PDFファイルで献立を取り込む予定でしたが、あまりにも作業時間が大幅になるため実装はせずに、openAIのみで献立を作成してます。

## サービスイメージがわかるようなスクリーンショット等
![image](https://github.com/user-attachments/assets/4a773e12-8b90-481a-ace5-3a1b055c2b6d)
![image](https://github.com/user-attachments/assets/bb9e9813-59da-4c5d-be38-b775162cbe2a)

**Comment by Tsuchiya2** [comment]
下記機能について確認ができませんでした。
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

---

https://github.com/user-attachments/assets/c0e56ed2-3e82-43b1-92ac-9c5004cc7ce5


・既に献立がある日付の別時間帯で献立を作成すると、既にあった献立が消えてしまいました。ご確認をお願いします。

・カレンダーに自分が作成したものではない、献立（12/3の朝）が表示されており、且つゴミ箱のアイコンが表示されており、削除できてしまいそうですが大丈夫でしょうか？

**Comment by hataboon** [comment]
・「同一の日付に違う時間帯で献立を作成すると既存の献立が削除される問題」は気づきませんでしたので、修正しテスト済みです。
・１２月３日の献立は手違いで表示されてしまいました。
・また、献立が削除可能な状態については私も実装していいのか迷い中であり、一旦、削除できる状態にしています。

**Comment by rdhdchloe** [comment]
アプリへアクセスすると以下の画面になってました。
ご確認お願いします。

![Screenshot 2024-12-21 at 10 02 02](https://github.com/user-attachments/assets/8bb6bbd2-c015-45f2-bbe2-15520d3f081f)

**Comment by hataboon** [comment]
こちらでは正常に動作します。
再デプロイしました。
再度ご確認をお願いします。

**Comment by rdhdchloe** [comment]
下記機能について確認ができませんでした。
・食材入力・栄養素に基づく献立生成
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

献立を作成を押してもずっとこの画面のままでした。
<img width="1188" alt="Screenshot 2024-12-21 at 10 57 28" src="https://github.com/user-attachments/assets/731eaa23-dc85-4ea0-9f87-d315302921c7" />

**Comment by hataboon** [comment]
修正しました。
食材に基づく生成は中止ににして、栄養素のみでの献立生成のみになります。
ご確認お願いします。

**Comment by hataboon** [comment]
修正しました。

**Comment by ippei-shimizu** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
